language: node_js
node_js:
- lts/*
- '11'
- '13'
- '14'
after_success: npm run coveralls
deploy:
  provider: npm
  email: info@iliocatallo.it
  api_key:
    secure: Aiy77LJp/wvkJkq1TCp9zEjgGy0elRL+GvPtYKHTT0EiX06zShiblCexGtLEkF4YnT3Bbi9QGKthd9Q7CZxQTiGjOzdC9RFGGQnsk0Hgw8peTMy9hgpZrn0hCRIiGsfgR7u3hK0Eu28t5LSUjhgxId6ZKtouwqg5Ol2Vbfrt9/0xSNiDkVO0b2eVcH3VVv/ZipstA1ZmGXcVk1Eqv2v4g5ZllRQQqERo5VyNqo9W7/FOzViz7QtEdhVcHZvudRF1IuLY9s3FawEEFuWs6daM5nIeRD3Zc2Pxk4RnnZN9wVG0iiosCRIP7ZMET0AlZOzFPjYFt+xjwYLgdX+QLNgVVk+M2smc8Lfznr57tYANoQC27zTL9NLXXO+ad92MZHA6ed8RUStyR2Xm+kG+kdUoqasdCmCr3r2BO07y+ixoC8MtXh5HG1qbAx6vTyByXnyP5Vjm083QEQSWzTuzxlF4aa1SpCNB34t3x3B6jxSRKgAydKOjqqsPVIMxmHQ7h2CncsH+H9uCgqrHm8yroXEyqSYLu3GwxtW2gOyBatbCpgyM3qGg2EUmp+57ZmukgQP7S8lK4ZKxDe/NnEIaSCD823tIKX0HCLEOLjnWOz6S7BH357RBwHi7GpfCLLVfj+iEDze06AIsixQaWkhLD77B6Gu49UWlQ6qE6i6jssWaU/A=
  on:
    tags: true
    repo: iliocatallo/typista
